# Generated by Django 4.2 on 2023-05-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='username',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
